name = "g2"
main = "cloudflare-worker.js"
compatibility_date = "2025-04-07"

# KV 命名空间绑定
kv_namespaces = [
  { binding = "URL_SHORTENER", id = "替换为你的KV命名空间ID" }
]

# 路由配置
routes = [
  { pattern = "g2.al/*", zone_name = "g2.al" }
]

# 环境变量配置
[vars]
VITE_SHORT_URL_DOMAIN = "g2.al" 