name = "g2"
main = "cloudflare-worker.js"
compatibility_date = "2025-04-07"

# 路由配置使用环境变量
# 确保在Cloudflare中已设置 VITE_SHORT_URL_DOMAIN 环境变量
routes = [
  { pattern = "$VITE_SHORT_URL_DOMAIN/*", zone_name = "$VITE_SHORT_URL_DOMAIN" }
]

# 环境变量配置
[vars] 