name = "g2"
main = "cloudflare-worker.js"
compatibility_date = "2025-04-07"

# 启用workers.dev域名
workers_dev = true

# 路由配置
routes = [
  { pattern = "g2.al/*", zone_name = "g2.al" }
]

# 环境变量配置
[vars]
VITE_SHORT_URL_DOMAIN = "g2.al"

[observability.logs]
enabled = true